### ISSUE TITLE
new velcro slot on baseplate

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Instagrain#104]
It would be nice to have a second velcro slot to secure the GPS wires. My most recent build ended up like this.. 
instead of running the velcro under the whole baseplate, it would be nice if there was just a set of slots.
![IMG_0681](https://user-images.githubusercontent.com/5330599/177182066-3eb4d728-0fff-44d9-9cd6-e83c11697d08.jpg)

**Comment by jacobstasiewicz** [comment]
.stp file in V3 folder
