### ISSUE TITLE
New case design

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Instagrain#106]
I am interested in the design of a new, smaller case.

Some notes:
- goal is to replace the GPS hat with a USB GPS reciever (i.e., the coaxial cable hole on top needs to be USB sized).. removing this hat will also allow a real RTC to be mounted, and for all the other wiring to use jumper cables directly on the RPi GPIO pins.
- remove coral holes on the case - mounts and usb-c hole... (coral can be mounted on a baseplate)
- remove trigger hole
- i really like the peg connection for the tent, and the camera setup, no need to change that. 
- I like the handles (and i even like the specific handles we have), but i woudl be fine with just one, or handle(s) on other sides, or smaller handles, etc.. 
- The 7 inch touchscreen is big, but it is nice, works super well, is easy to setup, and is made by RPi (which makes me think it might have a longer production life). we could find a smaller screen, but it would be nice to work with this size if at all possible...
- The Polycase WQ series, with the hinges are very nice. Would WQ-48 or WQ-50 work? I am also ok if we move to a case w/o hinges, like a WC or WP... (i want to stick with polycase b/c of the CNCing service.

**Comment by jacobstasiewicz** [comment]
The WQ-50 case is what I have already designed and measured. If I remember correctly this is the smallest case I could find that fits everything.

**Comment by ebgoldstein** [comment]
If you remove the handles, can it get smaller (ie, a WP case, which has more size options)?

**Comment by ebgoldstein** [comment]
i guess for the sake of latches, the WQ case is the best...

**Comment by jacobstasiewicz** [comment]
Note: 48 is 2mm to small for the screen, but could be a future option with a different screen size

**Comment by jacobstasiewicz** [comment]
This issue is done, needs to be closed once stp/step files are sent off and approved
