### ISSUE TITLE
Instructions to build V3 camera (autofocus and/or HW camera) based on changes

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Instagrain#118]
Notes so far:
- no coral
- USB GPS
- RTC

**Comment by ebgoldstein** [comment]
this issue should close with a tagged release (v0.2) and likely also a link to a RPi OS image on zenodo

**Comment by ebgoldstein** [comment]
this also might result in upgrading the software to the new RPi OS and the new camera software

**Comment by jacobstasiewicz** [comment]
software upgrade is going to be needed for arducam

**Comment by ebgoldstein** [comment]
basic instructions are up... mostly copied from v2

**Comment by ebgoldstein** [comment]
this should reflect v3 w/ HW cam and v3 w/ autofocus camera

**Comment by ebgoldstein** [comment]
ok, i have updated the GH repo and the wiki to reflect:

v1 is 3d printed
v2 is large enclosure
v3 is small enclosure

Software is essentially identical for all of these versions

There are now 2 folders for v3 software: ` v3_HQ` and `v3_auto` - these are substantially different, based on the HQ nad autofocus cameras..
