### ISSUE TITLE
Plate for mounting parts to make it easy for dev work

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Instagrain#135]
In the course of discussing a 'dev camera', it turns out we just need a simple way to prototype cameras and do development work that do not rely on having an actual enclosure...

the RPi can be attached to the RPI screen (with the included standoffs).. and then we just need like a plate that can attach to the hood (w/ peg holes) and then holes for the camera standoff stuff...

_Originally posted by @ebgoldstein in https://github.com/UNCG-DAISY/Instagrain/issues/133#issuecomment-1252577400_

**Comment by ebgoldstein** [comment]
via @jacobstasiewicz 

"has raspberry pi on left, battery slots on right, button on top, camera mounting holes, and the peg holes for the hood.. little 5mm  bumps on the bottom for when the hood or camera are not on"

![plate1](https://user-images.githubusercontent.com/5330599/191545145-877763ac-5def-41a7-8ea1-6330ed87420f.png)
![plate2](https://user-images.githubusercontent.com/5330599/191545155-bc46fded-898f-4a29-b699-a74c0c486203.png)

**Comment by jacobstasiewicz** [comment]
Added file to github
