### ISSUE TITLE
Case Improvements

### ISSUE THREAD

**Issue by jacobstasiewicz** [UNCG-DAISY/Instagrain#142]
- [ ] fix handle cutout diameters
- [ ] baseplate cutout for handle screw ends
- [ ] one boss removed for velcro cutout
- [ ] brainstorm camera connection ideas
- [ ] any other ideas to make it easier to build (i.e., wiring the camera light to the Pi)

**Comment by ebgoldstein** [comment]
i think these are non-essential at this time, so i am closing
