### ISSUE TITLE
System time from GPS time, (or integrate an RTC?)

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/Instagrain#91]
I think the instructions for the RTC are not correct.. i can work on this

**Comment by ebgoldstein** [comment]
https://forums.adafruit.com/viewtopic.php?f=50&t=182292&p=885900&hilit=gps+hat+rtc#p885900

**Comment by jacobstasiewicz** [comment]
The csv file is now updated from the gps in UTC, but it would still be nice to figure out the RTC

**Comment by ebgoldstein** [comment]
let's keep this open, and i can rename this issue

**Comment by ebgoldstein** [comment]
new rtc has been ordered.. this would mean swapping out {GPS hat+connector+antenna} for {RTC + USB-GPS).. this would require a bigger hole on the top case (for USB cable).

**Comment by ebgoldstein** [comment]
I think this is not needed anymore with the RTC in V3, the GPS time recorded in the sample spreadsheet, and the 5 digit hash code being used for the folder name
